### ISSUE TITLE
How to import?

### ISSUE THREAD

**Issue by holyspiritomb** [embark-theme/alacritty#2]
When I tried to import this theme in my `alacritty.yml`, it seemed to have no effect. I didn't even get an error.

In order for this theme to activate, I had to manually edit `embark.yml`.

I changed
> `schemes:`
> `  embark: &embark`
to `colors:` and then unindented every following line by one level. Then my alacritty's colors changed to the theme's.

If `embark.yml` can be imported as-is, please add instructions for how to import it. I've made an AUR pkgbuild for this theme and I'd like to include instructions for how to import it.

Additional information:
OS: Arch Linux
Kernel: 6.1.8-AMD-znver2
Alacritty version: 0.12.0-1
WM: sway 1:1.8.1-1 (wayland 1.21.0-2 & wlroots 0.16.2-1)

**Comment by skbolton** [comment]
Sorry @holyspiritomb I am just seeing this.
I would appreciate any help in fixing this if I caused an issue in 9a99e7add665f119b607c2b11bab646de1c59f9d
When I updated the palette to a new color I couldn't get it to apply correctly. When I looked around the community I saw examples doing if the way that I did in that pr. I am not an alacrity user so if there are changes that need to be made let me know, or open a pr.
